# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satellite_game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='City',
        ),
    ]
