# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellite_game', '0002_auto_20171208_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_name',
            field=models.CharField(default='test', max_length=256),
            preserve_default=False,
        ),
    ]
